name: compile latex CI
# This workflow runs the pipeline with the minimal test dataset to check that it completes without any syntax errors
on:
  push:
    branches:
      - dev
  pull_request:
  release:
    types: [published]

env:
  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
  NFT_VER: "0.9.5"
  NFT_WORKDIR: "~"
  NXF_ANSI_LOG: false

jobs:
  test:
    name: Run pipeline with test data
    runs-on: ubuntu-latest
    strategy:
      matrix:
        NXF_VER:
          - "25.10.2"
          - "latest-everything"
    steps:
      - name: Check out pipeline code
        uses: actions/checkout@v2

      - name: Install Nextflow
        uses: nf-core/setup-nextflow@v2
        with:
          version: "${{ matrix.NXF_VER }}"

      - name: Set up Python
        uses: actions/setup-python@e797f83bcb11b83ae66e0230d6156d7c80228e7c # v6
        with:
          python-version: "3.14"

      - name: Install nf-test
        uses: nf-core/setup-nf-test@v1
        with:
          version: "${{ env.NFT_VER }}"
          install-pdiff: true

      - name: Run nf-test
        shell: bash
        env:
          NFT_WORKDIR: ${{ env.NFT_WORKDIR }}
        run: |
          nf-test test \
            --profile=+test \
            --ci \
            --changed-since HEAD^ \
            --verbose \
            --tap=test.tap